In [ ]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
(3-1)/(50-1)


0.04081632653061224

In [ ]:
np.linspace(2, 3, 2)

array([2., 3.])

In [ ]:
np.linspace(2, 3, 3, retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [ ]:
a=np.linspace(2,3,3,retstep = True)
float(a[1])

0.5

In [ ]:
np.linspace(2,3,3,retstep = True,endpoint = False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [ ]:
(3-2)/3

0.3333333333333333

In [ ]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

## numpy 주요 함수

## zeros()

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2, 1))

In [ ]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

## ones()

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## eye()

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3, 4, 1)

## full()

In [ ]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## empty()

In [ ]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty([2, 3], dtype=int)

array([[          261946208,                   0, 4189038663854989856],
       [8104338779582374432, 8317419966641237601,     140400996712482]])

In [ ]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

## 배열과 스칼라와의 연산

In [ ]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a +2)
print(a - 2)
print(a * 2)
print(a / 2)


[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


## 배열과 배열의 연산

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

## 배열과 슬라이싱

In [ ]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]
a[-2, :]

array([18, 19, 20, 21, 22, 23])

## 2차원 배열의 첨자와 슬라이싱

In [ ]:
a[2:4]
a[1:5:2]
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

## 3차원 배열의 다양한 참조

In [ ]:
a[1]
a[:, 1]


array([ 1,  7, 13, 19, 25])

In [ ]:
a[..., 1]
a[1, ..., 1]

array(7)

In [ ]:
a[0, ...]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.arange(12).reshape(2, 3, 2)

In [ ]:
np.transpose(a)

array([[[ 0,  6],
        [ 2,  8],
        [ 4, 10]],

       [[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])

## 브로드캐스팅

In [ ]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 5])
a + b

array([11, 11, 10])

In [ ]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a * b

array([24, 28, 30])

In [ ]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [ ]:
x * b

array([[ 8, 14, 18],
       [32, 35, 36],
       [56, 56, 54]])

In [ ]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = np.arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [ ]:
from numpy import arange

a = arange(1, 4)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [ ]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
y = arange(1, 3)
y

array([1, 2])

## 고급 색인

In [ ]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[2, 3]]

array([2, 3])

In [ ]:
x[ [2, 3, 2, 5, 8] ]

array([2, 3, 2, 5, 8])

In [ ]:
x = np.arange(56).reshape(7, 8)

In [ ]:
int(x[0, 1])

1

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[...,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[ [0], [1] ]

array([1])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[[1, 3, 5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[[1, 3, 5],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[[1, 3], [2,2]]

array([10, 26])

In [ ]:
x[[1, 3], [2, 3]]

array([10, 27])

In [ ]:
x[[0, 2, 4], [1]]

array([ 1, 17, 33])

In [ ]:
x[[0, 2, 4], 1]

array([ 1, 17, 33])

In [ ]:
x[[0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [ ]:
a[[2, 3]][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])