## numpy.vstack

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [ ]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [ ]:
d = np.array([100, 200])
# np.vstack((a, b))  # This caused the error because 'a' has 2 columns and 'b' has 3 columns.

# To fix this, you need arrays with matching column counts.
# 'b_compatible' (available in your kernel) has 2 columns, matching 'a'.
np.vstack((a, b_compatible))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
d = np.array([100, 200]) # Modified d to have 2 elements to match the number of columns in 'a'
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

## numpy.hstack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [ ]:
# np.hstack((a, c)) # Original code caused ValueError due to mismatch in number of rows

# To fix, ensure arrays have the same number of rows.
# Here, we slice 'a' to match the number of rows in 'c'.
np.hstack((a[:2], c))

array([[ 0,  1, 10, 20],
       [ 2,  3, 30, 40]])

In [ ]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## 배열 결합 연산
np.column_stack() row_stack()





In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
np.column_stack == np.hstack

False

In [ ]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_6655/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

## 배열 결합 연산

concatenate()
stack()

In [ ]:
import numpy as np

a = np.array([1, 2])
a = np.array([3, 4])
a = np.array([5, 6])

In [ ]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np. arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_6655/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_6655/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

## 난수

In [ ]:
import numpy as np

rg = np.random.default_rng(12345)
rg.random()

0.22733602246716966

In [ ]:
rg.random()

0.31675833970975287

In [ ]:
rg.random(5)

array([0.79736546, 0.67625467, 0.39110955, 0.33281393, 0.59830875])

In [ ]:
rg.random((3,4))

array([[0.18673419, 0.67275604, 0.94180287, 0.24824571],
       [0.94888115, 0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286, 0.73392816]])

In [ ]:
rg.random((2, 3,4))

array([[[0.22013496, 0.08159457, 0.1598956 , 0.34010018],
        [0.46519315, 0.26642103, 0.8157764 , 0.19329439],
        [0.12946908, 0.09166475, 0.59856801, 0.8547419 ]],

       [[0.60162124, 0.93198836, 0.72478136, 0.86055132],
        [0.9293378 , 0.54618601, 0.93767296, 0.49498794],
        [0.27377318, 0.45177871, 0.66503892, 0.33089093]]])

In [ ]:
rg = np.random.default_rng(1)
rg.integers(low=0, high = 10,size = 3)

array([4, 5, 7])

In [ ]:
rg.integers(low=0, high=20, size=(3, 4))

array([[19,  0,  2, 16],
       [18,  4,  6, 17],
       [ 8,  5, 16,  5]])

In [ ]:
rg.integers(0, 20, size=(3, 4))

array([[ 8, 12, 10,  1],
       [ 0, 17, 15, 16],
       [10, 16,  6,  9]])

In [ ]:
rg.integers(1, 7, (3, 4))

array([[5, 1, 2, 1],
       [3, 6, 1, 3],
       [3, 6, 2, 4]])

In [ ]:
rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [ ]:
rg.standard_normal((3,4))

array([[-1.30315723,  0.90535587,  0.44637457, -0.53695324],
       [ 0.5811181 ,  0.3645724 ,  0.2941325 ,  0.02842224],
       [ 0.54671299, -0.73645409, -0.16290995, -0.48211931]])

## 배열 결합 연습

In [ ]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)

a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)

p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack( (a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack( (p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b,c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p,q,r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack([a,b,c])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.r_[p,q,r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])